# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot = {
    initrd = {
      availableKernelModules = ["nvme" "xhci_pci" "usb_storage" "sd_mod"];
      # kernelModules = ["amdgpu"];
    };

    # kernelParams = ["amdgpu"];



    kernelModules = ["kvm-amd"];
    kernelPackages = pkgs.linuxPackages_zen; # Comment it for default kernel
    extraModulePackages = [];
    # extraModulePackages = with config.boot.kernelPackages; [ wireguard ];
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/210a14f4-9c23-45d1-a221-8c903f8f718f";
      fsType = "ext4";
    };

    "/boot/efi" = {
      device = "/dev/disk/by-uuid/537E-7D5E";
      fsType = "vfat";
    };
    "/home/rohits/mydata" = {
      device = "/dev/disk/by-uuid/10f15eaf-0f70-4876-9bc0-abfa801c1dc5";
      fsType = "ext4";
    };
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
